services:
  mongo:
    image: mongo:7.0
    container_name: whatsapp_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: whatsapp_backend
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn whatsapp_bot:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: whatsapp_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      # Frontend will reach backend via host machine
      - VITE_API_BASE=http://127.0.0.1:8000
      - VITE_SOCKET_URL=http://127.0.0.1:8000
    volumes:
      - ./frontend:/app                    # Live code changes
      - frontend_node_modules:/app/node_modules  # Preserve installed dependencies
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  mongo_data:
  frontend_node_modules: