import React, { useState } from "react";
import { generateClientMessages } from "../api";

export default function GenerateClientMessages() {
  const defaultPrompt = `Compose a formal, professional, and polite email to a client providing an update on the management of their property. Include a clear subject line and email content that mentions the client and their property description, describing the activities performed. Keep the message concise and courteous, ending only with “Warm regards.” Do not include property ID or any additional signature details. Ensure the meaning remains exactly the same without adding any new information or context.`;

  const [date, setDate] = useState(""); // only date
  const [prompt, setPrompt] = useState(defaultPrompt);
  const [merchantId, setMerchantId] = useState("34137234-52fe-430c-a97d-df3e16525e71");
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  const handleGenerateMessages = async () => {
    if (!date || !prompt || !merchantId) {
      setErrorMessage("Please provide date, prompt, and merchant ID.");
      setResults([]);
      return;
    }

    setLoading(true);
    setErrorMessage("");
    setResults([]);

    try {
      // Convert date (YYYY-MM-DD) in browser local timezone to UTC midnight
      const [year, month, day] = date.split("-").map(Number);
      const localDate = new Date(year, month - 1, day, 0, 0, 0); // local midnight
      const utcDate = localDate.toISOString(); // UTC

      const data = await generateClientMessages(utcDate, prompt, merchantId);

      // Handle API errors in response
      if (data.error) {
        setErrorMessage(data.error);
        setResults([]);
      } else if (!data.processed || data.processed.length === 0) {
        setErrorMessage("No messages were generated by the API.");
        setResults([]);
      } else {
        setResults(data.processed);
        setErrorMessage("");
      }
    } catch (err) {
      setErrorMessage(err.response?.data?.error || err.message || "Failed to generate messages");
      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto mt-10 bg-white rounded-2xl shadow-lg p-6 border border-slate-200">
      <h2 className="text-2xl font-bold text-gray-800 mb-4">Generate Client Messages</h2>

    <div className="flex flex-col gap-4 mb-4 w-full">
      {/* Row 1: date + merchantId */}
      <div className="flex flex-row items-center gap-4 w-full">
      <input
        type="date"
        value={date}
        onChange={(e) => setDate(e.target.value)}
        className="border border-slate-300 rounded-md px-3 py-2"
      />

      <input
        type="text"
        value={merchantId}
        placeholder="Merchant ID"
        onChange={(e) => setMerchantId(e.target.value)}
        className="border border-slate-300 rounded-md px-3 py-2 flex-grow"
      />
    </div>


      {/* Row 2: prompt textarea (full width) */}
      <div className="w-full flex flex-col gap-4">
      <textarea
        value={prompt}
        placeholder="Enter prompt for OpenAI"
        onChange={(e) => setPrompt(e.target.value)}
        className="border border-slate-300 rounded-md px-3 py-2 w-full h-44 md:h-56 resize-none"
        rows={8}
      />

      <button
        onClick={handleGenerateMessages}
        disabled={loading}
        className={`px-4 py-2 rounded-md text-white font-medium transition ${
          loading ? "bg-green-300 cursor-not-allowed" : "bg-green-600 hover:bg-green-700"
        }`}
      >
    {loading ? "Generating..." : "Generate"}
    </button>
    </div>

    </div>


      {/* Show API error messages */}
      {errorMessage && <div className="mb-4 text-red-600">{errorMessage}</div>}

      {/* Show generated messages */}
      {results.length > 0 && (
        <div className="overflow-x-auto max-h-96 overflow-y-auto border-t border-slate-200 pt-2">
          <table className="w-full text-sm text-left text-gray-700">
            <thead className="bg-slate-100 sticky top-0">
              <tr>
                <th className="px-3 py-2">Client</th>
                <th className="px-3 py-2">Property</th>
                <th className="px-3 py-2">Activity Description</th>
                <th className="px-3 py-2">Generated Message</th>
              </tr>
            </thead>
            <tbody>
              {results.map((res, idx) => (
                <tr key={idx} className="border-b hover:bg-slate-50">
                  <td className="px-3 py-2">{res.client}</td>
                  <td className="px-3 py-2">{res.property}</td>
                  <td className="px-3 py-2">{res.activityDescription}</td>
                  <td className="px-3 py-2">{res.generatedMessage}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Show "No messages generated yet" only when no errors */}
      {results.length === 0 && !loading && !errorMessage && (
        <p className="text-gray-600">No messages generated yet.</p>
      )}
    </div>
  );
}
