import React, { useState } from "react";
import { generateClientMessages, sendActivityEmails } from "../api";

export default function GenerateClientMessages() {
  const defaultPrompt = `I am Kostas Arslanoğlu, i am the owner of the company . you write the message on my behalf and you sign by my name  . The email will start by saluting the client with its name and surname , the first raw of the message will start with title ,  stating the address and the name of the flat -  Compose a formal, professional, and polite email to a client providing an update on the management of their property. Include a clear subject line and email content that mentions the client and their property description, describing the activities performed. İn the end of the email you will say to the client that he will continue his communication with the department and the person who speaks up to now . The email that you will write is explanatory and confirms the follow up and the survailance of me  . Keep the message concise and courteous, ending only with “Saygılarımla ".  Ensure the meaning remains exactly the same without adding any new information or context. write all the message in turkish . you exctract info only from the activity description , you get the address the number of the flat and the neighborhood from property section and the person information from contact section  . you will not translate any other information from property only adress flat number and neighbourhood , you will not translate any other informatino from the contact info , you will extract only name and surname`;

  const [date, setDate] = useState("");
  const [prompt, setPrompt] = useState(defaultPrompt);
  const [merchantId, setMerchantId] = useState("34137234-52fe-430c-a97d-df3e16525e71");
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(false);
  const [emailLoading, setEmailLoading] = useState(false);

  const [generateError, setGenerateError] = useState("");
  const [emailResponse, setEmailResponse] = useState("");

  const handleGenerateMessages = async () => {
    if (!date || !prompt || !merchantId) {
      setGenerateError("Please provide date, prompt, and merchant ID.");
      setResults([]);
      return;
    }

    setLoading(true);
    setGenerateError("");
    setResults([]);

    try {
      const [year, month, day] = date.split("-").map(Number);
      const localDate = new Date(year, month - 1, day, 0, 0, 0);
      const utcDate = localDate.toISOString();

      const data = await generateClientMessages(utcDate, prompt, merchantId);

      if (data.error) {
        setGenerateError(data.error);
        setResults([]);
      } else if (!data.processed || data.processed.length === 0) {
        setGenerateError("No messages were generated by the API.");
        setResults([]);
      } else {
        setResults(data.processed);
        setGenerateError("");
      }
    } catch (err) {
      setGenerateError(err.response?.data?.error || err.message || "Failed to generate messages");
      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  const handleSendEmails = async () => {
  if (!merchantId || !date) {
    setEmailResponse("Date and Merchant ID are required to send emails.");
    return;
  }

  setEmailLoading(true);
  setEmailResponse("");

  try {
    const [year, month, day] = date.split("-").map(Number);
    const localDate = new Date(year, month - 1, day, 0, 0, 0);
    const utcDate = localDate.toISOString();

    const data = await sendActivityEmails(merchantId, utcDate);
      if (data.error) {
        setEmailResponse(data.error);
      } else {
        setEmailResponse(`${data.sent_count} emails processed successfully.`);
        console.log("Send emails results:", data.processed);
      }
    } catch (err) {
      setEmailResponse(err.response?.data?.error || err.message || "Failed to send emails");
    } finally {
      setEmailLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto mt-10 bg-white rounded-2xl shadow-lg p-6 border border-slate-200">
      <h2 className="text-2xl font-bold text-gray-800 mb-4">Generate Client Messages</h2>

      {/* Input Row: date + merchantId */}
      <div className="flex flex-col gap-4 mb-4 w-full">
        <div className="flex flex-row items-center gap-4 w-full">
          <input
            type="date"
            value={date}
            onChange={(e) => setDate(e.target.value)}
            className="border border-slate-300 rounded-md px-3 py-2"
          />
          <input
            type="text"
            value={merchantId}
            placeholder="Merchant ID"
            onChange={(e) => setMerchantId(e.target.value)}
            className="border border-slate-300 rounded-md px-3 py-2 flex-grow"
          />
        </div>

        {/* Prompt Textarea */}
        <div className="w-full flex flex-col gap-4">
          <textarea
            value={prompt}
            placeholder="Enter prompt for OpenAI"
            onChange={(e) => setPrompt(e.target.value)}
            className="border border-slate-300 rounded-md px-3 py-2 w-full h-44 md:h-56 resize-none"
            rows={8}
          />

          {/* Generate Messages Button full width */}
          <button
            onClick={handleGenerateMessages}
            disabled={loading}
            className={`w-full px-4 py-2 rounded-md text-white font-medium transition ${
              loading ? "bg-green-300 cursor-not-allowed" : "bg-green-600 hover:bg-green-700"
            }`}
          >
            {loading ? "Generating..." : "Generate"}
          </button>
        </div>
      </div>

      {/* Generate Messages Error */}
      {generateError && <div className="mb-4 text-red-600">{generateError}</div>}

      {/* Generated Messages Table */}
      {results.length > 0 && (
        <div className="overflow-x-auto max-h-96 overflow-y-auto border-t border-slate-200 pt-2">
          <table className="w-full text-sm text-left text-gray-700">
            <thead className="bg-slate-100 sticky top-0">
              <tr>
                <th className="px-3 py-2">Client</th>
                <th className="px-3 py-2">Property</th>
                <th className="px-3 py-2">Activity Description</th>
                <th className="px-3 py-2">Generated Message</th>
              </tr>
            </thead>
            <tbody>
              {results.map((res, idx) => (
                <tr key={idx} className="border-b hover:bg-slate-50">
                  <td className="px-3 py-2">{res.client}</td>
                  <td className="px-3 py-2">{res.property}</td>
                  <td className="px-3 py-2">{res.activityDescription}</td>
                  <td className="px-3 py-2">{res.generatedMessage}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Show "No messages generated yet" */}
      {results.length === 0 && !loading && !generateError && (
        <p className="text-gray-600">No messages generated yet.</p>
      )}

      {/* Send Activity Emails Button & Response */}
      <div className="mt-4 flex flex-col gap-2">
        <button
          onClick={handleSendEmails}
          disabled={emailLoading}
          className={`w-full px-4 py-2 rounded-md text-white font-medium transition ${
            emailLoading ? "bg-blue-300 cursor-not-allowed" : "bg-blue-600 hover:bg-blue-700"
          }`}
        >
          {emailLoading ? "Sending Emails..." : "Send Activity Emails"}
        </button>

        {/* Email Response / Error */}
        {emailResponse && (
          <p className={`mt-2 ${emailResponse.includes("successfully") ? "text-green-600" : "text-red-600"}`}>
            {emailResponse}
          </p>
        )}
      </div>
    </div>
  );
}
